CHANGELOG.md, docs/conf.py, docs/userguide/intro/about.md, docs/userguide/intro/data.md
Updating docs for public release.
- Setting up version switch
- Updating image links to asset store
=> Public docs update

CHANGELOG.md, earth2studio/models/px/fengwu.py, earth2studio/models/px/pangu.py, earth2studio/models/px/sfno.py, pyproject.toml
- Updating min modulus version
- Update model dep errors to link to docs
=> Update Modulus Version

docs/userguide/components/datasources.md, earth2studio/run.py, test/run/test_deterministic.py, test/run/test_diagnostic.py, test/run/test_ensemble.py
- Fixing bug in workflows where device parameter would not do anything
- Fixing issue with code snippet in dataloader docs
Closes: https://github.com/NVIDIA/earth2studio/issues/28
Closes: https://github.com/NVIDIA/earth2studio/issues/30
=> Fixing device control in workflows

docs/modules/datasources.rst
=> add WB2Climatology to docs

CHANGELOG.md, earth2studio/lexicon/ifs.py, test/statistics/test_metrics.py
Improving IFS data source lexicon to include all available pressure levels based on ECMWF's documentation.
Closes: https://github.com/NVIDIA/earth2studio/issues/32
=> Expanding IFS datasource pressure levels

docs/userguide/about/install.md, docs/userguide/support/troubleshooting.md
ORT 1.18.0 seems to be causing some problems, updated to suggest 1.17.1
=> Updating install docs with ORT version

test/models/px/test_dlwp.py, test/models/px/test_fcn.py, test/models/px/test_fengwu.py, test/models/px/test_fuxi.py, test/models/px/test_pangu.py, test/models/px/test_sfno.py
Fixes some issues seen with PyTest and running full prognostic models.
=> Adding clear caching to package tests

docs/userguide/components/datasources.md, earth2studio/lexicon/wb2.py
Fix Weather bench 2 relative humidity.
Closes: https://github.com/NVIDIA/earth2studio/issues/56
=> Weather Bench 2 Data fix

earth2studio/models/px/fengwu.py, earth2studio/models/px/fuxi.py, earth2studio/models/px/pangu.py, earth2studio/models/utils.py, test/models/px/test_fuxi.py
Moving onnx utils for some third-party px into a common file.
Closes: https://github.com/NVIDIA/earth2studio/issues/47
=> Common ONNX utils

.github/workflows/blossom-ci.yml
=> Updating workflow with more secure user check

docs/userguide/about/install.md, earth2studio/statistics/rmse.py, examples/01_deterministic_workflow.py, examples/02_diagnostic_workflow.py, examples/03_ensemble_workflow.py, examples/04_corrdiff_inference.py, examples/05_ensemble_workflow_extend.py, examples/06_model_perturbation_hook.py, examples/07_seasonal_statistics.py, examples/08_distributed_manager.py, examples/extend/01_custom_prognostic.py, examples/extend/02_custom_diagnostic.py, examples/extend/03_custom_datasource.py, pyproject.toml
- Fixing CorrDiff bare metal with an optional import for einops via pip install .[corrdiff].
- Bug fix to corrdiff example
- Improved examples to all create outputs dir if none exists.
- Adding [parallel] install option for xarray to install Dask if not present.
Closes: https://github.com/NVIDIA/earth2studio/issues/62
=> CorrDiff import and example fix

CHANGELOG.md, CITATION.cff, docs/_static/switcher.json, earth2studio/__init__.py
=> Version 0.2.0 update

CHANGELOG.md, CITATION.cff, docs/_static/switcher.json, earth2studio/__init__.py
=> Update main version to 0.3.0a0

CHANGELOG.md, docs/modules/datasources.rst, earth2studio/data/__init__.py, earth2studio/data/base.py, earth2studio/data/gfs.py, earth2studio/data/utils.py, earth2studio/utils/time.py, test/data/test_gfs.py, test/utils/test_time.py
=> Forecast Sources

pyproject.toml
=> Adding cartopy to doc deps

CHANGELOG.md, earth2studio/data/arco.py, earth2studio/data/utils.py, earth2studio/lexicon/arco.py, pyproject.toml, test/data/test_arco.py, test/statistics/test_crps.py
Some prep work to refactor ARCO into a form that makes it better for Apache Beam pipelines as well as adding async IO to speed up. Some higher level design decisions made:
- The atomic function used inside data sources is now `fetch_array(time, variable) -> np.nd.array`. This allows this single line to be integrated into other pipelines instead of the asyncio one. This also encourages the building of the xarray object to live elsewhere.
- Number of async io tasks is limited by the property `async_process_limit`, this prevents people from hammering the API with 100s of requests at once. I used some code I found online and tested to act as a sort of un ordered map. I intentionally left this out of constructor because I don't want this too exposed to users because I do not want people …
=> ARCO Asyncio and Apache Beam Prep

CHANGELOG.md, earth2studio/data/arco.py, earth2studio/data/cds.py, earth2studio/data/gfs.py, earth2studio/data/hrrr.py, earth2studio/data/ifs.py, earth2studio/data/imerg.py, earth2studio/data/rx.py, earth2studio/data/utils.py, earth2studio/data/wb2.py, pyproject.toml
- Fixes gcs local caching
- Datasources cache location can now be controls with EARTH2STUDIO_CACHE
- Fixing ecmwf opendata version, 0.2.0 doesnt work
Closes: https://github.com/NVIDIA/earth2studio/issues/96
=> Data source cache improvements

earth2studio/data/arco.py, earth2studio/data/wb2.py
=> Adding vanilla bandit skips

CHANGELOG.md, earth2studio/models/dx/corrdiff.py, pyproject.toml
=> 0.2.0 rebase into main

earth2studio/io/netcdf4.py, earth2studio/io/zarr.py, test/io/test_netcdf4.py, test/io/test_zarr.py
Also adding some tests for the overwrites
Closes: https://github.com/NVIDIA/earth2studio/issues/105
=> Improving write errors for Zarr and NetCDF 

CHANGELOG.md, earth2studio/utils/coords.py, test/utils/test_coords.py
Reworking some of the logic in map coords to map slices more efficient.
Adjusting and expanding tests with PR: https://github.com/NVIDIA/earth2studio/pull/109
=> Skip interpolation in map_coords when possible

README.md
=> Update README.md URL

docs/modules/datasources.rst, earth2studio/data/__init__.py, earth2studio/data/gefs.py, earth2studio/lexicon/gefs.py, test/data/test_gefs.py
=> Adding msl to GEFS surface

earth2studio/data/gefs.py, earth2studio/lexicon/gefs.py
=> GEFS MSL fix

CHANGELOG.md, docs/modules/datasources.rst, earth2studio/data/__init__.py, earth2studio/data/hrrr.py, test/data/test_hrrr.py
Adding HRRR Forecast data source
=> HRRR Forecast Datasource

earth2studio/models/auto/ngc.py
=> Security scan fixes

examples/08_distributed_manager.py
=> Changing data source of example 8

CHANGELOG.md, earth2studio/__init__.py
=> Version Update for 0.3.0

pyproject.toml
=> Adding missing dependencies for doc builds

.gitlab-ci.yml
=> Fixing Gitlab CI branch reference

earth2studio/lexicon/gefs.py
=> Adding additional GEFS vars

CHANGELOG.md, earth2studio/data/gfs.py, earth2studio/lexicon/gefs.py, earth2studio/lexicon/gfs.py
Adding tp to GFS_FX
Closes: https://github.com/NVIDIA/earth2studio/issues/153
=> Adding tp to GFS_FX datasource

CHANGELOG.md, README.md, docs/userguide/about/install.md, docs/userguide/components/io.md, docs/userguide/support/faq.md, earth2studio/data/cds.py, earth2studio/data/hrrr.py, earth2studio/data/ifs.py, earth2studio/io/zarr.py, earth2studio/models/auto/package.py, pyproject.toml, test/data/test_cds.py
Multi-bug clean up:
- https://github.com/NVIDIA/earth2studio/issues/146
- https://github.com/NVIDIA/earth2studio/issues/141
- https://github.com/NVIDIA/earth2studio/pull/142
=> Multiple Bug Fixes

CHANGELOG.md, earth2studio/data/gfs.py, earth2studio/data/hrrr.py, earth2studio/lexicon/__init__.py, earth2studio/lexicon/hrrr.py, pyproject.toml, test/data/test_gfs.py, test/data/test_hrrr.py
Adding the NCEP data location for GFS which get updated faster than AWS. Useful for real time forecast applications.
=> Adding NCEP data repo support in GFS data source

.github/workflows/blossom-ci.yml, .pre-commit-config.yaml, CHANGELOG.md, docs/userguide/about/install.md, docs/userguide/support/troubleshooting.md, earth2studio/__init__.py, earth2studio/data/gfs.py, earth2studio/data/hrrr.py, earth2studio/lexicon/__init__.py, earth2studio/lexicon/hrrr.py, earth2studio/utils/interp.py, pyproject.toml, test/data/test_gfs.py, test/data/test_hrrr.py
=> 0.4.0-rc merge into main

.github/workflows/blossom-ci.yml, CHANGELOG.md, pyproject.toml
Adding few users to authorized CI runners.
Fixes: https://github.com/NVIDIA/earth2studio/issues/170
=> Blossom Auth CI update

earth2studio/models/px/stormcast.py
Use a more robust version check in the StormCast call
=> Better modulus version guard in stormcast

CHANGELOG.md, earth2studio/__init__.py
=> Version updates for 0.4.1

CHANGELOG.md, earth2studio/data/__init__.py, earth2studio/data/rand.py, earth2studio/data/utils.py, earth2studio/models/dx/corrdiff.py, earth2studio/models/px/stormcast.py, earth2studio/run.py, examples/04_corrdiff_inference.py, examples/09_stormcast_example.py, examples/10_stormcast_ensemble_example.py, test/data/test_random.py, test/models/dx/test_corrdiff.py
* This PR updates the CorrDiff example to incorporate changes due to the addition of multidimension support.
* This PR adds a StormCast example that uses the deterministic forecast method from `earth2studio.run`.
* This PR adds forecast data source support to `fetch_data`.
=> Update CorrDiff and add StormCast examples.

CHANGELOG.md, earth2studio/data/utils.py, earth2studio/io/netcdf4.py, earth2studio/statistics/crps.py, earth2studio/statistics/rank.py, earth2studio/statistics/rmse.py, test/io/test_netcdf4.py, test/statistics/test_crps.py, test/statistics/test_ranks.py
Fixes #180 
Fixes #181 
Fixes #182 
Fixes #185 
Fixes #186 
Fixes #190
=> Bug fixes for 0.5.0

.github/workflows/blossom-ci.yml
This PR adds saikrishnanc-nv to Blossom CI's yaml
=> Add saikrishnanc-nv to Blossom CI

earth2studio/data/utils.py
Remove statement that prints data array after successfully fetching data.
=> Remove print statement

Makefile, docs/userguide/about/install.md, pyproject.toml
Fixes: https://github.com/NVIDIA/earth2studio/issues/205
=> Fixing loading issue for SFNO

docs/userguide/about/install.md, earth2studio/data/arco.py, earth2studio/data/gefs.py, earth2studio/data/gfs.py, earth2studio/data/hrrr.py, earth2studio/lexicon/hrrr.py, earth2studio/lexicon/ifs.py, earth2studio/models/batch.py, earth2studio/models/px/sfno.py, earth2studio/models/px/stormcast.py, pyproject.toml
Closes: https://github.com/NVIDIA/earth2studio/issues/211
=> Fixing stormcast dependencies 

CHANGELOG.md, docs/userguide/about/data.md, earth2studio/utils/coords.py, test/utils/test_coords.py
Adds basic coordinate roll support to map_coords.
=> Adding roll coord mapping support

pyproject.toml
=> Adding StormCast deps to all option

CHANGELOG.md, earth2studio/models/auto/ngc.py, earth2studio/models/dx/corrdiff.py, earth2studio/utils/interp.py, pyproject.toml, test/models/test_auto_models.py
- Fixes CorrDiff deps from physicsnemo release
- Closes: https://github.com/NVIDIA/earth2studio/issues/202
=> Updating NGC Download method for new APIs

earth2studio/data/ncar.py
=> Update max workers for ncar to 4

CHANGELOG.md, earth2studio/data/hrrr.py, earth2studio/data/ncar.py, pyproject.toml, test/data/test_hrrr.py
- Migrate HRRR datasource back to Herbie for better support of sources since Zarr is still limited
- removed the async functions to make sure things run in  a Jupyter notebook.
- Update NCAR to use concurrent futures not multiprocessing
Closes: https://github.com/NVIDIA/earth2studio/issues/193
Closes: https://github.com/NVIDIA/earth2studio/issues/191
=> HRRR Datasource Update

earth2studio/io/zarr.py
Fixing type bug in zarr IO for newer Zarr versions.
=> Type fix for Zarr 3.0

CHANGELOG.md, Makefile, earth2studio/data/gefs.py, earth2studio/data/gfs.py, earth2studio/data/hrrr.py, earth2studio/data/rx.py, earth2studio/data/utils.py, earth2studio/data/wb2.py, earth2studio/io/zarr.py, earth2studio/models/dx/corrdiff.py, earth2studio/models/px/stormcast.py, examples/07_seasonal_statistics.py, examples/08_distributed_manager.py, examples/09_stormcast_example.py, examples/10_stormcast_ensemble_example.py, examples/extend/01_custom_prognostic.py, examples/extend/02_custom_diagnostic.py, examples/extend/03_custom_datasource.py, test/perturbation/test_gaussian.py
Closes: https://github.com/NVIDIA/earth2studio/issues/224
Closes: https://github.com/NVIDIA/earth2studio/issues/226
=> Zarr 3.0 Fixes in Data sources, IO and Examples

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Makefile, earth2studio/__init__.py, earth2studio/data/gefs.py, earth2studio/data/gfs.py, earth2studio/data/hrrr.py, earth2studio/data/rx.py, earth2studio/data/utils.py, earth2studio/data/wb2.py, earth2studio/io/zarr.py, earth2studio/models/dx/corrdiff.py, earth2studio/models/px/stormcast.py, examples/07_seasonal_statistics.py, examples/08_distributed_manager.py, examples/09_stormcast_example.py, examples/10_stormcast_ensemble_example.py, examples/extend/01_custom_prognostic.py, examples/extend/02_custom_diagnostic.py, examples/extend/03_custom_datasource.py, test/io/test_zarr.py, test/perturbation/test_gaussian.py
=> 0.5.0-rc rebase

docs/userguide/about/install.md
=> Update install.md for Makani fork

.gitlab-ci.yml, CONTRIBUTING.md, Makefile, earth2studio/perturbation/gaussian.py, test/Dockerfile, test/io/test_kv.py, test/lexicon/test_hrrr_lexicon.py, test/models/test_auto_models.py, test/perturbation/test_gaussian.py, test/utils/test_coords.py
Migrating the backend CI to run on Gitlab runners and have the stage commands listed in the gitlab-ci.yml.
Also improves the state / progress on the Github side and makes the uploaded log easier to read.
=> CI Overhaul

CHANGELOG.md, Makefile, docs/modules/models.rst, docs/userguide/about/install.md, earth2studio/models/px/__init__.py, earth2studio/models/px/aurora.py, earth2studio/models/px/microsoft_aurora.py, examples/01_deterministic_workflow.py, pyproject.toml, test/models/px/test_aurora.py
Add Aurora model. 
Closes: https://github.com/NVIDIA/earth2studio/issues/200
=> Add Aurora model

.github/ISSUE_TEMPLATE/bug_report.yml, README.md, docs/userguide/about/install.md, docs/userguide/developer/dependency.md, docs/userguide/index.md, earth2studio/utils/imports.py, test/utils/test_imports.py
Cleaning up a few items from the uv update:
Closes: https://github.com/NVIDIA/earth2studio/issues/240
Closes: https://github.com/NVIDIA/earth2studio/issues/241
Closes: https://github.com/NVIDIA/earth2studio/issues/242
Closes: https://github.com/NVIDIA/earth2studio/issues/243
=> uv clean up work

.gitlab-ci.yml, Makefile, test/conftest.py, test/models/px/test_aurora.py, test/models/px/test_dlwp.py, test/models/px/test_sfno.py, test/models/test_auto_models.py
Updating CI to include the use of model cache.
To refresh the cache use the internal job that can be manually ran
Closes: https://github.com/NVIDIA/earth2studio/issues/236
=> Ci Model Cache update

docs/userguide/about/install.md, docs/userguide/support/faq.md, earth2studio/__init__.py, earth2studio/models/auto/ngc.py
Improved the auth method for NGC access a little with a better warning.
Also adds a FAQ section for when encountering NGC auth errors.
Closes: https://github.com/NVIDIA/earth2studio/issues/250
=> NGC Auth fixes

CHANGELOG.md, docs/modules/models.rst, docs/userguide/developer/overview.md, docs/userguide/support/faq.md, earth2studio/lexicon/gfs.py, earth2studio/models/dx/__init__.py, earth2studio/models/dx/derived.py, test/models/dx/test_derived.py
Adding additional diagnostic for relative humidity on surface
Closes: https://github.com/NVIDIA/earth2studio/issues/249
Closes: https://github.com/NVIDIA/earth2studio/issues/252
Test script:
```python
from datetime import datetime
from earth2studio.data import GFS, CDS, prep_data_array
from earth2studio.models.dx import DerivedRHDewpoint
ds = GFS()
level = "2m"
input_data = ds(datetime(2023,1,1), [f"t{level}", f"d{level}", f"r{level}"])
dsa = CDS()
era5_data = dsa(datetime(2023,1,1), [f"r1000"])
model = DerivedRHDewpoint()
input, input_coords = prep_data_array(input_data.sel(variable=[f"t{level}", f"d{level}"]))
output, output_coords = model(input, input_coords)
import torch
output_no_ice = torch.load("no_ice_output.pt")
import matplotlib.pyplot as plt
fig, ax = plt.subplots(2, 2, …
```
=> Adding Surface relative humidity diagnostic

.gitlab-ci.yml, docs/_static/switcher.json, docs/conf.py, docs/userguide/about/install.md, earth2studio/models/px/interpmodafno.py, test/Dockerfile, test/models/px/test_aurora.py
=> DevOps and Doc Updates

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, README.md, docs/_static/switcher.json
=> Version updates for RC

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, README.md, docs/_static/switcher.json, earth2studio/__init__.py
=> 0.6.0 Rebase into Main

CITATION.cff
Removing version from citation file, users can add if needed.
=> Citation file fix

.gitlab-ci.yml, examples/10_stormcast_ensemble_example.py, examples/13_cyclone_tracking.py, pyproject.toml, uv.lock
Closes: https://github.com/NVIDIA/earth2studio/issues/268
=> Example Fixes

.gitignore, CHANGELOG.md, Makefile, docs/modules/perturbation.rst, earth2studio/perturbation/hcbv.py, examples/08_distributed_manager.py, examples/11_huge_ensembles.py, examples/12_temporal_interpolation.py, examples/13_cyclone_tracking.py, test/perturbation/test_hcbv.py
- Improves the HENs perturbation to support a single batch.
- Adds a HENs mini example for sphinx gallery with the goal to just show how to load the checkpoints and use the perturbation method. Not be 100% consistent with the paper.
=> HENS Mini Example

CHANGELOG.md, earth2studio/models/px/aurora.py
PR on HF repo open:
https://huggingface.co/microsoft/aurora/discussions/1
Removes the pickle load from the Aurora model, since having pickle load isnt good practice in our code base (should downstream model packages use pickle, that is up to them).
For now points to my PR branch with the stripped out numpy files.
=> Removing pickle load from Aurora

CHANGELOG.md, earth2studio/data/arco.py, earth2studio/data/utils.py
Still using nest_asyncio to help with notebooks, need to understand the fsspec solution more.
https://github.com/fsspec/filesystem_spec/blob/master/fsspec/asyn.py#L108
Zarr 3.0 still disable atm because of the caching issue that exists current, but have tested this.
Seems to be around 10x faster when pulling something like SFNO initial conditions
=> ARCO update for async

docs/modules/models.rst, docs/userguide/about/install.md, docs/userguide/support/troubleshooting.md
=> Install Doc Updates / Improvements

.gitlab-ci.yml
Adding schedule option in CI and some clean up to get coverage reports working.
Closes: https://github.com/NVIDIA/earth2studio/issues/264
=> Adding schedule CI rule

docs/templates/datasource.rst, docs/userguide/components/datasources.md, earth2studio/data/gfs.py
=> Data Doc Fixes

earth2studio/data/wb2.py
Closes: https://github.com/NVIDIA/earth2studio/issues/305
=> Fixing WB2 docs

Makefile, docs/userguide/advanced/lexicon.md, earth2studio/lexicon/gfs.py, examples/10_stormcast_ensemble_example.py, examples/13_cyclone_tracking.py, examples/14_dlesym_example.py
=> Misc Doc Fixes

earth2studio/data/gefs.py, earth2studio/data/gfs.py, earth2studio/data/hrrr.py, test/data/test_wb2climate.py, test/data/test_wb2era5.py
closes: https://github.com/NVIDIA/earth2studio/issues/316
=> Data source Python 3.10 fixes

.gitlab-ci.yml, docs/userguide/about/install.md
=> Update docs with newer PyTorch Image

CHANGELOG.md, earth2studio/data/ncar.py, test/data/test_ncar.py
Closes: https://github.com/NVIDIA/earth2studio/issues/334
=> NCAR Bug Fixes

earth2studio/io/zarr.py
Fixes issue with asyncio loop handling when initializing multiple `ZarrBackend` objects in the same process.
Do I get an award for the smallest PR to earth2studio?
=> Read coords from zarr using explicit API

recipes/hens/src/hens_perturbation.py
Updates HENSPerturbation class to improve code clarity by:
- Making parameter naming consistent between methods (vars → perturbed_var)
- Clarifying DataSource usage in docstrings
=> [HENS] Improve docstrings and parameter naming consistency

earth2studio/utils/imports.py, examples/15_cbottle_generation.py
=> CBottle Example fix

CHANGELOG.md, earth2studio/data/arco.py, earth2studio/data/gefs.py, earth2studio/data/gfs.py, earth2studio/data/hrrr.py, earth2studio/data/wb2.py, test/data/test_hrrr.py
Improving async file system stores to be properly initialized within async loop if present.
Notes:
- https://filesystem-spec.readthedocs.io/en/latest/async.html#using-from-async
- https://github.com/fsspec/s3fs/issues/943
=> GCS Fsspec Initialization Fixes

CHANGELOG.md, test/models/test_auto_models.py
=> NGC Test Fix

docs/userguide/about/install.md
=> Adding Install for E2Grid via Pip for Cbottle

docs/userguide/developer/documentation.md
Closes: https://github.com/NVIDIA/earth2studio/issues/386
=> Update examples userguide info

test/Dockerfile
Updating CI base container to latest PyTorch.
Hopefully fixes issues seeing with runner machines using CUDA 12.9 to getting GPU access.
=> Bumping CI base container

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, docs/userguide/about/install.md, earth2studio/__init__.py, earth2studio/models/auto/ngc.py, earth2studio/models/auto/package.py, pyproject.toml, recipes/template/README.md, recipes/template/pyproject.toml, test/models/test_auto_models.py, uv.lock
=> 0.8.1 rebase

docs/userguide/about/install.md
Adding some missing install steps for cbottle for pip users.
Closes: https://github.com/NVIDIA/earth2studio/issues/398
=> CBottle Install Edits

earth2studio/models/px/dlesym.py
Minor fix on DLESyM insolation tensor method docstring
=> Touch-up dlesym insolation docstring

docs/userguide/about/install.md
=> Adding system recommendation section to install page

README.md, docs/_static/css/nvidia-sphinx-theme.css, earth2studio/models/dx/cbottle_sr.py, earth2studio/models/dx/corrdiff.py, examples/13_cyclone_tracking.py, examples/README.rst
Closes: https://github.com/NVIDIA/earth2studio/issues/263
+ some random fixes
https://github.com/NickGeneva/earth2studio/tree/ngeneva/readme_update?tab=readme-ov-file
NOTE: I have intentionally left our a recipe link at the top until they have additional internal testing.
=> ReadMe Update

docs/userguide/about/install.md
Closes: https://github.com/NVIDIA/earth2studio/issues/445
=> Fixing SFNO install docs

examples/07_seasonal_statistics.py
=> Seasonal Example URL Update

.github/workflows/blossom-ci.yml
=> Update CI users

docs/userguide/about/install.md, docs/userguide/support/troubleshooting.md, pyproject.toml
Closes: https://github.com/NVIDIA/earth2studio/issues/466
Also does temp update to cbottle fork for main branch. Will revert when needed changes are upstreamed.
=> Updating install docs

docs/userguide/about/install.md
Closes: https://github.com/NVIDIA/earth2studio/issues/471
=> Improving install docs notes

earth2studio/models/dx/cbottle_tc.py, earth2studio/models/px/cbottle_video.py, pyproject.toml, test/models/dx/test_cbottle_tc.py, uv.lock
Based on this example: https://github.com/NickGeneva/cBottle/blob/ngeneva/guidance_improv/examples/tc_guidance_inference.py
=> Adding ICON modality support for TC guidance model in CBottle
