NVIDIA/earth2studio

CHANGELOG.md
docs/modules/perturbation.rst
earth2studio/perturbation/__init__.py
earth2studio/perturbation/lagged.py
test/perturbation/test_lagged.py

Adds the ability to perturb using a lagged ensemble perturbation strategy.

Add lagged ensemble perturbation method

---

CHANGELOG.md
earth2studio/io/kv.py
earth2studio/io/netcdf4.py
earth2studio/io/xarray.py
earth2studio/io/zarr.py
test/io/test_kv.py
test/io/test_netcdf4.py
test/io/test_xarray.py
test/io/test_zarr.py

- Added the ability to reload zarr and netcdf backends
- Added the ability to read from an IOBackend
- NetCDF reads are now mode='r+' instead of 'w'.

add reading ability and reloading netcdf/zarr stores

---

CHANGELOG.md
docs/modules/statistics.rst
earth2studio/statistics/__init__.py
earth2studio/statistics/acc.py
earth2studio/statistics/base.py
earth2studio/statistics/crps.py
earth2studio/statistics/moments.py
earth2studio/statistics/rank.py
earth2studio/statistics/rmse.py
test/statistics/test_ranks.py

This PR adds the rank histogram function.
This PR also fixes #49 
This PR makes `reduction_dimensions` as a property of statistics and metrics. This
is useful becomes some workflows need to keep track of how statistics/metrics manipulate
the input coordinates to produce output coordinates.
This PR fixes some typos in the documentation
This PR improves utility of __str__

Add rank histogram

---

CHANGELOG.md
docs/modules/datasources.rst
earth2studio/data/__init__.py
earth2studio/data/hrrr.py
earth2studio/data/wb2.py
earth2studio/lexicon/wb2.py
test/data/test_wb2climate.py
test/data/test_wb2era5.py
test/models/px/test_sfno.py

Adds ERA5 part of weatherbench as a data source. Largely copy paste of ARCO code but include two lower resolution versions as well.
Slower than ARCO it seems but provide relative humidity and also tp06 which is great for running some models. Also improves available in HRRR with an off line check.
Closes: https://github.com/NVIDIA/earth2studio/issues/43
I am also disabling the package test for now, it fails on vanilla pytorch container

Adding WeatherBench2 ERA5 data source

---

CHANGELOG.md
docs/userguide/advanced/auto.md
earth2studio/models/auto.py
earth2studio/models/dx/climatenet.py
earth2studio/models/dx/corrdiff.py
earth2studio/models/dx/precipitation_afno.py
earth2studio/models/px/dlwp.py
earth2studio/models/px/fcn.py
earth2studio/models/px/fengwu.py
earth2studio/models/px/fuxi.py
earth2studio/models/px/pangu.py
earth2studio/models/px/sfno.py
pyproject.toml
test/models/dx/test_corrdiff.py
test/models/test_auto_models.py

Refactoring of how the `earth2studio.models.px.auto.Package` class works to lean more into Fsspec to use more of their existing caching system as well as provide better downloading feedback for users via tqdm. Also adds better ability to customize caching directly in model, namely default can not hash file names to make cache readable. I made the call to decouple this from Modulus file system, which operates a little differently, because it takes too long to upstream.
**There is a slight "bug"/limitation in Fsspec which is the reason this took long to figure out related to the call back for caching**. Had to  extend the caching cache to fix.
Closes: https://github.com/NVIDIA/earth2studio/issues/46
Closes: https://github.com/NVIDIA/earth2studio/issues/59

Model Package Update to improve Model file caching

---

.pre-commit-config.yaml
CHANGELOG.md
Makefile
docs/modules/datasources.rst
earth2studio/data/ifs.py
earth2studio/data/imerg.py
earth2studio/lexicon/__init__.py
earth2studio/lexicon/base.py
earth2studio/lexicon/imerg.py
earth2studio/models/auto.py
pyproject.toml
test/data/test_imerg.py

Adding IMERG data source, the first data source using NASA's earth data portal. Validated output / transforms by comparing WB2 and IMERG at specific time. Both have the same larger structures indicating transforms are correct.
```python
from earth2studio.data import WB2ERA5
date = datetime.datetime(year=2002, month=10, day=1)
wbds = WB2ERA5(cache=False)
imergds = IMERG(cache=False)
wb_data = wbds(time=date, variable=["tp06"])
im_data = imergds(time=date, variable=["tp"])
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
fig, ax = plt.subplots(1, 2)
ax[0].imshow(wb_data.values[0, 0] + 0.001, norm=LogNorm(vmin=0.0001, vmax=1))
ax[0].set_title("ERA5")
ax[1].imshow(im_data.values[0, 0] + 0.001, norm=LogNorm(vmin=0.0001, vmax=1))
ax[1].set_title("IMERG") …
```

Adding IMERG Data source

---

docs/userguide/about/install.md
docs/userguide/developer/documentation.md
docs/userguide/developer/overview.md
docs/userguide/developer/testing.md
docs/userguide/index.md
earth2studio/models/auto.py
earth2studio/models/batch.py
earth2studio/perturbation/lagged.py
test/conftest.py
test/models/px/test_dlwp.py
test/models/px/test_fcn.py
test/models/px/test_sfno.py
test/models/test_auto_models.py

Cleaning up bugs:
Closes: https://github.com/NVIDIA/earth2studio/issues/72
Adds ability to control timeout of known remote stores using a environment variable for slow internet connections. Each remote store sets this is a different way... so theres not elegant solution. Also improved unit testing and fixed issue in S3 package.
Closes: https://github.com/NVIDIA/earth2studio/issues/71
Removed recursive check that appeared from copying the batch function decorator. Basically would call output_coords inside the batch coords decorator that would get it stuck. Simple fix. I still think we maybe want to change input_coords to a function that returns a new dictionary.
Closes: https://github.com/NVIDIA/earth2studio/issues/69
Adding testing page with pytest commands in the docs.
Attempts to fixxx …

Pytest improvement, Bug Fixes and Documentation Update

---

earth2studio/data/imerg.py
earth2studio/lexicon/base.py
earth2studio/lexicon/imerg.py

IMERG provides total precip in mm, add modifier in lexicon to move to m.
https://arthurhou.pps.eosdis.nasa.gov/Documents/IMERG_TechnicalDocumentation_final.pdf
```python
import datetime
from earth2studio.data import IMERG, ARCO
date = datetime.datetime(year=2002, month=10, day=1)
wbds = ARCO(cache=False)
imergds = IMERG(cache=False)
wb_data = wbds(time=date, variable=["tp"])
im_data = imergds(time=date, variable=["tp"])
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
fig, ax = plt.subplots(1, 2)
ax[0].imshow(wb_data.values[0, 0] + 0.001, norm=LogNorm(vmin=0.0001, vmax=0.1))
ax[0].set_title("ERA5 tp")
ax[1].imshow(im_data.values[0, 0] + 0.001, norm=LogNorm(vmin=0.0001, vmax=0.1))
ax[1].set_title("IMERG tp")
plt.savefig("test.png")
```

Updating IMERG total precip data to meters

---

earth2studio/models/dx/identity.py
earth2studio/perturbation/brown.py
earth2studio/perturbation/bv.py
earth2studio/perturbation/gaussian.py
earth2studio/perturbation/spherical.py
test/perturbation/test_brown.py
test/perturbation/test_bv.py
test/perturbation/test_gaussian.py
test/perturbation/test_spherical_gaussian.py

This is a backward compatible PR that adds the ability to pass broadcastable tensors as noise amplitudes in relevant perturbation methods.

Add tensor noise amplitude parameters for perturbation methods

---

earth2studio/io/kv.py
earth2studio/io/netcdf4.py
earth2studio/io/xarray.py

This PR removes `non_blocking=True` from `.to()` statements that were causing hard-to-trace IO issues.

Remove non-blocking IO writes

---

earth2studio/data/arco.py
earth2studio/data/cds.py
earth2studio/data/gfs.py
earth2studio/data/hrrr.py
earth2studio/data/ifs.py
earth2studio/data/imerg.py
earth2studio/data/wb2.py

Jupyter notebooks have a asyncio loop running by default which makes calling a async function from a sync function difficult. Namely blocking asyncio calls such as, `run_until_complete` or `run_until_complete` cannot be used. To get around this the data source creates a new thread for the call to run its own asyncio loop on.
Closes: https://github.com/NVIDIA/earth2studio/issues/103

Making Asyncio ARCO runnable in notebook

---

CHANGELOG.md
earth2studio/data/wb2.py
earth2studio/data/xr.py
test/data/test_xr.py

Made it so that local copies of WB2 Climatology can be used with existing WB2 objects.
Changed the structure of `data.xr` objects so that keyword arguments can be passed in the object instantiate method.

add local option to WB2 climatology

---

CHANGELOG.md
earth2studio/data/hrrr.py
earth2studio/lexicon/hrrr.py

Updating HRRR total precip to be the hourly product in the forecast system. Not the cumulative.
Simplified the lexicon a little.

HRRR TP Update

---

earth2studio/perturbation/__init__.py
earth2studio/perturbation/gaussian.py

Adding correlated spherical Gaussian noise, as was used in the [HENS method](https://arxiv.org/abs/2408.03100).

Gaussian Perturbation from HENS paper

---

CHANGELOG.md
docs/modules/utils.rst
earth2studio/models/dx/corrdiff.py
earth2studio/utils/interp.py
test/utils/test_interp.py

* Add interpolation between arbitrary 2D lat-lon grids as `earth2studio.utils.interp.LatLonInterpolation`. This is implemented as a `torch.nn.Module` because initializing the mapping between the grids can be a bit slow but after that the interpolation of the values is very fast.
* Move the interpolation function from the CorrDiff implementation to `earth2studio.utils.interp` for easier reuse in e.g. other CorrDiff implementations.
* Add test for `LatLonInterpolation`.

Interpolation for arbitrary grids

---

earth2studio/io/kv.py
earth2studio/io/netcdf4.py
earth2studio/io/xarray.py
earth2studio/io/zarr.py
earth2studio/utils/__init__.py
earth2studio/utils/coords.py
pyproject.toml
test/io/test_kv.py
test/io/test_netcdf4.py
test/io/test_xarray.py
test/io/test_zarr.py
test/utils/test_coords.py

This PR allows the handling of coordinates that are more than 1-dimensional. A common example are curvilinear coordinates systems where lat/lon grids are 2-dimensional.
With this PR, the IO system, in order to continue being compatible with xarray, will create 1-dimensional enumerations of the multidimensional coordinates and save them as dimensions to the IO backend while the 2-dimensional coordinates will be saved as arrays.

Add multidimension array IO compatibility

---

earth2studio/models/px/sfno.py
earth2studio/models/px/stormcast.py
examples/09_stormcast_example.py
examples/10_stormcast_ensemble_example.py

Doing some minor doc fixes for stormcast example and API docs.
Got them rendered and pushed.

Stormcast docs and example touch up

---

earth2studio/models/auto/ngc.py
test/models/test_auto_models.py

Fixing bug that occurs when calling the newer NGC apis where it returns seperate short term download URLs similar to the private api. This passed originally because I had a bug in the ngc model file system that would not request specific files for public models, rather the whole repo. This has been fixed
Closes: https://github.com/NVIDIA/earth2studio/issues/217

NGC Public Model Download Bug Fix

---

Makefile
earth2studio/io/zarr.py
test/io/test_zarr.py

- Fixing Zarr IO when accessing dimension names
- Adding Zarr 3.0 support for pytest
- Updating doc build to be multicore hopefully

Fixing Zarr access to dimension names

---

recipes/hens/src/hens_ensemble.py
recipes/hens/src/hens_utilities.py

The default for initialising EnsembleBase was set to cpu and device pass was omitted in hens_run.py, ie the pipeline only ran on the CPU. Fixed this by defaulting device to None.
Updating the model dict always happened, even if no update needed. Fixed this as well, and moved the "old" model to cpu to free GPU memory. delteing it directly would be better, but couldn't track down all other instances that existed, hence the hack.

HENS Recipe: Model loading updates

---

earth2studio/lexicon/arco.py

Including all of the pressure levels <= 1 hPa for z, t, u, v and q variables.
No new dependencies

Adding more vertical levels to the ARCO lexicon

---

earth2studio/io/kv.py
earth2studio/io/netcdf4.py
earth2studio/io/xarray.py
earth2studio/io/zarr.py
examples/05_ensemble_workflow_extend.py

This small PR migrates `np.in1d` to `np.isin` in order to resolve the deprecation warnings:
```python
DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
```

Update numpy array comparisons to use isin

---

CHANGELOG.md
earth2studio/data/base.py
earth2studio/data/gfs.py
earth2studio/data/hrrr.py
earth2studio/lexicon/hrrr.py
pyproject.toml
test/data/test_hrrr.py
test/lexicon/test_hrrr_lexicon.py
uv.lock

round two, this time with HRRR. Similar overhaul as GFS focuses on complete async and interfacing directly with the grib files to get significant speed ups
Sanity check:
```python
from datetime import datetime, timedelta
from earth2studio.data.hrrr import HRRR
from earth2studio.lexicon import HRRRLexicon
import time
import random
start = time.time()
dtime = [datetime(2023,2, 23, 18), datetime(2024,8, 12, 0)]
common_variables = list(set(HRRRLexicon.VOCAB.keys()))
common_variables.sort()
random.seed(0)
variables = random.sample(list(common_variables), len(common_variables))
ds = HRRR(cache=False)
da = ds(time=dtime, variable=variables)
print(f"Time taken: {time.time() - start:.2f} seconds")
da.to_netcdf("hrrr_new.nc", engine="h5netcdf")
```
Checked with:
```python
import xarray as xr
import …
```

HRRR Async Refactor

---

CHANGELOG.md
Makefile
earth2studio/data/wb2.py
earth2studio/lexicon/__init__.py
earth2studio/lexicon/arco.py
earth2studio/lexicon/wb2.py
test/data/test_arco.py
test/data/test_wb2climate.py
test/data/test_wb2era5.py
test/lexicon/test_wb2_lexicon.py

Same deal as ARCO, but limits WB2 to zarr 3.0 and up. ARCO supports both but not dealing with both here. Too messy. Also adding to lexicons.
As usual validated it with this script:
```python
import random
import time
from earth2studio.data import WB2ERA5, WB2ERA5_121x240, WB2ERA5_32x64, WB2Climatology
from earth2studio.lexicon import WB2Lexicon#, WB2ClimatetologyLexicon
from datetime import datetime
import time
start = time.time()
ds = WB2ERA5(cache=False)
dtime = [datetime(2010, 2, 12, 18), datetime(1992, 8, 12, 0), datetime(1992, 8, 12, 0)]
common_variables = list(set(WB2Lexicon.VOCAB.keys()))
common_variables.sort()
random.seed(0)
variables = random.sample(list(common_variables), len(common_variables))
da = ds(time=dtime, variable=variables)
print(f"Time taken: {time.time() - …
```

WB2 Async Zarr updates

---

CHANGELOG.md
earth2studio/perturbation/gaussian.py
test/perturbation/test_gaussian.py

Generalizing correlated Gaussian perturbation to support high dimensional input tensors (such as having lead times)

CorrelatedSphericalGaussian Generalization

---

earth2studio/perturbation/gaussian.py

- Fixed type annotation for `length_scale` parameter from `int` to `float` to match actual usage in code
- Updated unit specification from kilometers to meters to match actual implementation
- Updated docstrings for CorrelatedSphericalGaussian
- closes https://github.com/NVIDIA/earth2studio/issues/328

docstring update for CorrelatedSphericalGaussian/Field

---

earth2studio/models/dx/wind_gust.py
recipes/hens/src/hens_ensemble.py

- Hens recipe runs now also without TC tracking in config
- Changed cache folder name of windgustnet from climatenet to windgustnet

Fix windgust cache location and TC tracking in HENS recipe

---

CHANGELOG.md
earth2studio/models/px/stormcast.py

Bumps the default package version for StormCast. Package is now the publicly-visible one released under Earth-2 team on NGC, no longer using the legacy Modulus naming; model weights are the same.
New package version also fixes a bug in the model package conditioning variable list which swapped the order of `msl` and `sp`, causing stagnant forecasts in certain initial conditions.

StormCast package update

---

CHANGELOG.md
earth2studio/models/auto/ngc.py
test/models/test_auto_models.py

Corrects problem with the latest NGC SDK version that changes an API related to construction of the model asset URL. I remove the reliance on that method entirely in favor of just a cleaner impementation for both public and private assets. Also updated test to be a little better.
Also silenced more warnings the package spams and supports passing without NGC_CLI_API_KEY set.
Closes: https://github.com/NVIDIA/earth2studio/issues/396
I manually tested this for both:
```bash
earth2studiolocal-ngeneva@ipp2-2268:~/earth2studio$ uv pip install ngcsdk==3.152.2
Resolved 40 packages in 212ms
Uninstalled 1 package in 46ms
Installed 1 package in 47ms
- ngcsdk==3.158.1
+ ngcsdk==3.152.2
earth2studiolocal-ngeneva@ipp2-2268:~/earth2studio$ uv run pytest -s test/models/test_auto_models.py …
```

NGC SDK fixes

---

earth2studio/data/arco.py
earth2studio/data/gefs.py
earth2studio/data/gfs.py
earth2studio/data/hrrr.py
earth2studio/data/wb2.py

Fixes async data source initialization to be better in notebooks (so theres no annoying runtime warning), basically moves the nested asyncio patch into the constructor rather than the call
Before:
After:

Async data source notebook fixes

---

earth2studio/io/async_zarr.py

Fixed some syntax incompatibly between 3.12 and 3.10. As well as supporting Zarr 2.0 installs (had types that were Zarr 3.0 specific)

3.10 / Zarr 2.0 fixes for Async Zarr backend

---

CHANGELOG.md
docs/userguide/about/install.md
docs/userguide/developer/documentation.md
examples/01_deterministic_workflow.py
examples/02_diagnostic_workflow.py
examples/03_ensemble_workflow.py
examples/04_corrdiff_inference.py
examples/05_ensemble_workflow_extend.py
examples/06_model_perturbation_hook.py
examples/07_seasonal_statistics.py
examples/08_distributed_manager.py
examples/09_stormcast_example.py
examples/10_stormcast_ensemble_example.py
examples/11_huge_ensembles.py
examples/12_temporal_interpolation.py
examples/13_cyclone_tracking.py
examples/14_dlesym_example.py
examples/15_cbottle_generation.py
examples/16_cbottle_super_resolution.py
examples/17_io_performance.py
examples/README.rst
examples/extend/01_custom_prognostic.py
examples/extend/02_custom_diagnostic.py
examples/extend/03_custom_datasource.py
test/_ci/run_examples.sh
test/_ci/sync_version.sh

This PR addresses the long standing problem of needing additional dependencies / specific groups for each example.
Leveraging UV, we can add meta data that will essentially create a mini venv when running the script.
https://docs.astral.sh/uv/guides/scripts/#declaring-script-dependencies
`uv run example_name.py` now creates a isolated venv and loads needed deps.
I've added this meta data to all examples.
If nothing else this will spell out the dependencies needed for people to manually pip install.
- Added a drop down on the main example page with some information.
- Added CI script for UV running all examples which will be used in nightly pipeline
- Updated versioning bash script that will also tag the installs for examples for a given version of the docs
- Updated example developer docs …

Adding uv script dependencies to examples

---

earth2studio/models/px/dlesym.py

Uses the length of ocean output times to chunk ocean coupled inputs, rather than input times. Does not change behavior of current default package since the output times are same length as the input times, but this should be more flexible/correct for custom or future DLESyM variants.

Use ocean output times for ocean coupling

---

CHANGELOG.md
earth2studio/data/gfs.py
earth2studio/data/hrrr.py
test/data/test_hrrr.py

Adds check for lead times not on 6 hour interval for HRRR, also improves error message when grib index files / data is missing for GFS and HRRR.
Closes: https://github.com/NVIDIA/earth2studio/issues/387
Closes: https://github.com/NVIDIA/earth2studio/issues/393

Fixing HRRR lead time catches and improving error messages for grib index fails
